services:
  postgres:
    env_file: ".env"
    image: postgres:latest
    network_mode: host
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  
  redis:
    image: redis:latest
    network_mode: host
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

  minio:
    image: minio/minio:latest
    env_file: ".env"
    network_mode: host
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data
    volumes:
      - miniodata:/data

  adminer:
    image: adminer:latest
    ports:
      - "8080:8080"
    network_mode: host
    

volumes:
  pgdata:
    driver: local
  redisdata:
    driver: local
  miniodata:
    driver: local


